### ISSUE TITLE
Working with Terraform 

### ISSUE THREAD

**Issue by ppiccolo** [upcmd/up#17]
I'm working with **up** to call some terraform state and **up** is fantastic tool to do this but, I'm noticing that when terraform exit with an error, I cant see the error description, where i'm wrong. 

this is my **main* task  (very simple)
```yaml
  - name: Core_deploy
    desc: Run terraform apply to deploy all core VM(s)
    task:
      - func: call
        dvars:
          - name: args
            value: "-var-file={{.terraform_common}} -auto-approve"
        do: essential.apply
```

this is my **essential** module
```yaml
  - name: apply
    task:
      - func: shell
        do:
          - terraform init
          - terraform apply {{.args}}
```

and this is the output in case of errors
```
module.vm.vsphere_virtual_machine.vm["essential-salt-master"]: Refreshing state... [id=422eb435-1c5a-d003-9366-9462efd1776e]
module.vm.vsphere_virtual_machine.vm["essential-lb"]: Refreshing state... [id=422ee8a1-2007-a50b-db2e-ae765f520f68]
module.vm.vsphere_virtual_machine.vm["essential-zabbix"]: Refreshing state... [id=422e8d39-338c-c6c0-89b0-b09eaced3b85]
      exec wait -> exit status 1
      exit status 1
 .. failed(suppressed if it is not the last step)
 WARN: [Not rescued in task level] - [please assess the panic problem and cause, fix it before re-run the task]
task finally ->   ERROR: Failed And Not Ignored! [You may want to continue and ignore the error]
```

any suggestion ? 

tnx

**Comment by stephencheng** [comment]
@ppiccolo 

Firstly, UPcmd was designed for the  purpose to use the tools like terraform, right choice 👍 

A couple of things for you to untangle and see things more clearer:

1. when you run the command, do specify different verbose level, it's your best friend

eg, 

```

up ngo => gives bare minimal only information, which is the default level of v

up ngo -v vvv => gives you the visibility of cached vars/objects etc

up ngo -v vvvv => gives you the visibility of cached vars/objects etc + hints of what original shell command with template + hints of rendered plain shell command passed and executed

up ngo -v vvvvv => gives the debug and stack trace

``` 

2. when you use dvars, you can always use the flag: -v to see the immediate render result, in you caes:

-v means that it will show the rendered result in verbose level of "v" to reveal the info, this matches with default command without specifying any verbose level, or you can use -vvv to match: up ngo -v vvv

```
        dvars:
          - name: args
            value: "-var-file={{.terraform_common}} -auto-approve"
            flags:
              - v
```

3. By looking at the error, it says: the exit status is 1, which is a result of terraform apply the_rendered_args

Apply the debug/verbose from item 1 /2 and see what's the command being passed in

4. For the exception handling, you have 3 weapons:

* ignoreError flag
* Rescue (not recommended unless you know what you do, we always encourage fail fast and capture errors in CI or integration test phase in non prod env
* use Finally to cleanup

check out these docs:

https://upcmd.netlify.app/flow-controll/f0171/
https://upcmd.netlify.app/flow-controll/f0172/
https://upcmd.netlify.app/flow-controll/c0172/
https://upcmd.netlify.app/flow-controll/c0173/
https://upcmd.netlify.app/flow-controll/c0174/
https://upcmd.netlify.app/flow-controll/c0175/

I am happy to assist you through this, just let me know how it goes

PS.

Glad to see someone is actually using the very advanced module. May I know that if you intend to share your code within teams of your organisation? or open source it?
