### ISSUE TITLE
Pure local vars

### ISSUE THREAD

**Issue by ppiccolo** [upcmd/up#18]
Hi,

if I use `pure` flag for local variables, other variables are not taken into account, in my opinion will be better if variable that are external to the callee keep their original value.

Bye

**Comment by stephencheng** [comment]
based on the doco: 

> Sometimes, you want all the local vars to be pure and entired isolated in its own context, then you can setup a flag - pure to protect the local vars not to be impacted by the merging process
> 
> In this case, the local vars and its sub call stack's var stack will be all protected because the sub stack will be an extention of this func call

The design is to cut off the chain of variables casting downwards only. 

Normally:

(scope d|vars) -> (global d|vars) -> (local d|vars) --call--> (local d|vars)

With pure:

(scope d|vars) -> (global d|vars) --XX-- (local d|vars) --call--> (local d|vars), so it turns to:

 (local d|vars) --call--> (local d|vars)

I am not sure what your intension is, I do not quite follow what you said: the external vars to the called should keep original value, do you mean not to apply the overriding process?

If so, do you have use case for this?

**Comment by ppiccolo** [comment]
> Normally:
> 
> (scope d|vars) -> (global d|vars) -> (local d|vars) --call--> (local d|vars)
> 
> With pure:
> 
> (scope d|vars) -> (global d|vars) --XX-- (local d|vars) --call--> (local d|vars), so it turns to:
> 
> (local d|vars) --call--> (local d|vars)
> 

Ok the example clarify the actual implementation.


Taking as example the following (modified) showcase :

```yml
vars:
  a: aaa
  b: bbb
  c: ccc
tasks:
  - name: task
    desc: mock up test to test module.template rendering
    task:
      - func: cmd
        vars:
          b: bbb
          d: ddd
        flags:
          - pure
        do:
          - name: inspect
            desc: the vars in caller after invoking module task
            cmd:
              - exec_vars
              - exec_base_vars
          - name: assert
            cmd:
              #### Access to global variable a cause assertion failed because a is not defined              
              - '{{eq .a  "aaa"}}' 
              - '{{eq .b  "bbb"}}'
              - '{{eq .d  "ddd"}}'
      - func: call
        vars:
          e: first_level_eee
          f: first_level_fff
        flags:
          - pure
        do: substack
  - name: substack
    task:
      - func: cmd
        vars:
          f: fff
          g: ggg
          h: hhh
        do:
          - name: inspect
            desc: the vars in caller after invoking module task
            cmd:
              - exec_vars
              - exec_base_vars
```


Basically I like to access the globally defined `a` variable, and in case of `a` is defined in the `pure` local var context then only in this case override with the local value.  

You can think as a default variable value to be able to call the task as standalone block

Bye
