### ISSUE TITLE
(question): how to debug error codes from curl ?

### ISSUE THREAD

**Issue by lukasmrtvy** [upcmd/up#21]
Any idea, how to loop over curl result ( json ) and at the same check if curl reponse code = 200 or 201 ; else fail ?

Usually this is possible:
```
STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --request POST --header "PRIVATE-TOKEN: $MYTOKEN" "$URL)

if test $STATUSCODE -ne 201; then
  exit 1
fi
```
But I am not sure, if is possible to register stderr:
```
name: Main
task:
  - func: shell
    name: statuses
    do:
    - 'curl -sL --output /dev/stderr --write-out "%{http_code}"  -H "PRIVATE-TOKEN: {{ .gltoken }}" "{{ .glapiurl }"'
    reg: statuses_result
  - func: cmd
    do:
    - name: fail
    if: '{{eq .statuses_result.Code 200 or eq .statuses_result.Code 201 }}'
  - func: shell
    name: loop
    do:
    - 'echo {{ .loopitem.id }}'
    loop:
    - "{{ statuses_result.Stderr }}"
```
