### ISSUE TITLE
Interrupt shell process gracefully when up process interrupted 

### ISSUE THREAD

**Issue by llCorvinSll** [upcmd/up#22]
Hi. I want to setup up for development environment and add commands to it. 
For example start ```docker-compose up```
with something like this 
```
tasks:
  - name: dev_up
    task:
    - func: shell
      do:
      - cd {{.docker_dir}} && docker-compose up
```

but when i press ctr-c in shell up process stops immediately and not clean containers like in normal shell. 
I thin this is because  docker-compose process not receive ctrl-c command
