### ISSUE TITLE
(feat): Support varsfile in global scope & task scope

### ISSUE THREAD

**Issue by ifraixedes** [upcmd/up#28]
I'm starting to use this tool for one new setup I'm working on.

I want to break up the up ymal file into several ones and I was thinking I'd like to have a file where to put all the global variables rather than doing it in the `up.yml`. At the same time, I thought that it would be nice to also allow to use of a vars file at the task level.

Let me put an example:

Initial structure:

`up.yml`
```yaml
vars:
  username: ivan
tasks:
  - name: Main
     task:
       - func: shell
         do:
            - echo 'My username is: {{ .username }}'
```

Moving the vars to a file.

`vars.yml`
```yaml
vars:
  username: ivan
```

Using the `vars` file in a specific task. __This works!__

`up.yml`
```yaml
tasks:
  - name: Main
     task:
       - func: shell
         varsfile: vars.yml
         do:
            - echo 'My username is: {{ .username }}'
```

Using the `vars` file as globals. __This doesn't work__

`up.yml`
```yaml
varsfile: vars.yml
tasks:
  - name: Main
     task:
       - func: shell
         varsfile: vars.yml
         do:
            - echo 'My username is: {{ .username }}'
```

Using the `vars` file for each task under the same name. __This doesn't work__

`up.yml`
```yaml
tasks:
  - name: Main
     varsfile: vars.yml
     task:
       - func: shell
         varsfile: vars.yml
         do:
            - echo 'My username is: {{ .username }}'
```

I'm wondering if those cases that the `varsfile` doesn't work because of a specific reason and if there is another way to define the variables in a separate file for not having all of them in the `up.yml` file.
