### ISSUE TITLE
(feat): allow fail, timeout, retry, always run tasks

### ISSUE THREAD

**Issue by lukasmrtvy** [upcmd/up#9]
Would be nice to have possiblity to add:

- timeout 
- retry 
- allow_fail
- allow_exitcodes
- always run post task ( similar to https://docs.gitlab.com/ee/ci/yaml/#yaml-anchors-for-before_script-and-after_script )
- always run pre task 

options to tasks.

```
    tasks:
    - name: pre
      task:
      - func: shell
        do:
        - printf 'Prepare Env'
       always: pre
    - name: task
      task:
      - func: shell
        do:
        - sleep 60
       timeout: 10
       retries: 3
       allow_fail: true
       allow_exitcodes: 
       - 128
    - name: post
      task:
      - func: shell
        do:
        - printf 'Cleanup Env'
      always: post
```

Thanks

**Comment by stephencheng** [comment]
To address these one by one:

- timeout

Do  you have a supporting case? 

What I can think of this is in the case of a synchronised call, the server end is taking long time to process.

In this case, it should fall back to how the client tool is talking to the server, eg, 

```
curl https://fantatic.resource.com/myfile
```

The design of UPcmd is to try to collaborate and try to simplify the usage of multiple threads etc, I have got the thoughts here: https://upcmd.netlify.app/ideas_and_faq/concurrency/

It is technically possible and it is a strength of golang, but do we need it?

Continue above case, the responsibility should be really the client tool to deal with the timeout, rather than UPcmd.

Use this in shell func, problem should be solved:

```
curl --max-time 5.5 https://example.com/
```

Aslo see the [recommend tools](https://upcmd.netlify.app/ideas_and_faq/cli_tools/)


- retry

No need an implementation, the loop cmd + sleep cmd will do

https://upcmd.netlify.app/cmd-func/c0087/

You might need to generate an array for the time being as it requires that to iterate through, let me know if you like some thing like while without specifying the loop var, if so please raise as a feature

- allow_fail

I don't get this, could you explain a little bit more?

Currently, you can ignoreError, it actually allows to fail and continue, see https://github.com/upcmd/up/blob/master/up.yml, I use it to ignore not supported build and move on

- allow_exitcodes

No change required for this, you can achieve this by:

1. ignoreError
2. capture the result.Code then evaluate it to do whatever you like

- always run post task and pre task 

I have this in the plan already, would you mind creating this as a feature

Thanks

**Comment by stephencheng** [comment]
@lukasmrtvy PS. what's the purpose of the pre-task? I could understand the always run post-task is to clean up resources usage, close file handler etc, why do we need pre-task? Any use case?

Would below be okay?

```
tasks: 

- name: Main
  task:
    - func: call
       do:
         - pre-task
         - my-task-to-do-business
         - post-task
  
- 
  name: pre-task
  task:

- 
  name: post-task
  task:

- 
  name: my-task-to-do-business
  task:

```
